@Ejercicio1api_HostAddress = http://localhost:5221

GET {{Ejercicio1api_HostAddress}}/weatherforecast/
Accept: application/json

###

### Registrar un nuevo objeto encontrado
POST {{Ejercicio1api_HostAddress}}/ObjetosPerdidos
Content-Type: application/json

{
  "descripcion": "Paraguas negro",
  "categoria": "Accesorios",
  "lugarEncontrado": "Boleteria 2",
  "fechaEncontrado": "2026-09-25"
}

### Obtener todos los objetos
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos
Accept: application/json

### Obtener un objeto por ID
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/1
Accept: application/json

### Modificar los datos de un objeto
PUT {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/1
Content-Type: application/json

{
  "descripcion": "Mochila azul con cuadernos y cartuchera",
  "categoria": "Equipaje",
  "lugarEncontrado": "Plataforma 5",
  "fechaEncontrado": "2026-09-10"
}

### Eliminar un registro
DELETE {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/3

### Buscar objetos por descripcion
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/buscar?descripcion=mochila
Accept: application/json

### Filtrar objetos por categoria
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/categoria/Ropa
Accept: application/json

### Objetos que todavia no fueron reclamados
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/no-reclamados
Accept: application/json

### Objetos encontrados despues de una fecha
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/desde?fecha=2026-09-12
Accept: application/json

### Objetos del mas reciente al mas antiguo
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/recientes
Accept: application/json

### Marcar un objeto como reclamado
PUT {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/1/reclamar?nombrePersona=Juan Lopez

### Resumen de cantidades
GET {{Ejercicio1api_HostAddress}}/ObjetosPerdidos/resumen
Accept: application/json

###
